
# Assignment 7-NumPy & Pandas

## 1.Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [10]:
import numpy as np
num_array=np.arange(1,11)
print("Numpy array with numbers from 1 to 10",num_array)

Numpy array with numbers from 1 to 10 [ 1  2  3  4  5  6  7  8  9 10]


In [9]:
# Array after reshaping
num_array=num_array.reshape(2,5)
print("Array after reshaping",num_array)

Array after reshaping [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## 2.Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [14]:
# creating array containing numbers from 1 to 20
no_array=np.array(range(1,21))
no_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
# Extracting elements between index 5th and 15th 
no_array[6:15]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

# 3.Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

In [59]:
# Creating pandas series
import pandas as pd
dict={'apple':3,'banana':2,'orange':1}
pd_series=pd.Series(dict)
pd_series

apple     3
banana    2
orange    1
dtype: int64

In [61]:
# Adding new key value pair pears:4
pd_series['pears']=4
pd_series

apple     3
banana    2
orange    1
pears     4
dtype: int64

# 4.Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

In [63]:
data={'Name':['Sam','Ethan','Noah','Prince','Chris','Royce','Raechal','Mary','Antony','Maria'],
      'Age':[35,30,28,30,34,25,34,23,34,35],
      'Gender':['Male','Male','Male','Male','Male','Male','Female','Female','Male','Female']}
df_frame=pd.DataFrame(data)
df_frame

Name  Age  Gender
0      Sam   35    Male
1    Ethan   30    Male
2     Noah   28    Male
3   Prince   30    Male
4    Chris   34    Male
5    Royce   25    Male
6  Raechal   34  Female
7     Mary   23  Female
8   Antony   34    Male
9    Maria   35  Female

# 5.Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [65]:
df_frame['Occupation']=['Programmer','Manager','Analyst','Programmer','Manager','Analyst','Programmer','Manager','Analyst','Analyst']
df_frame

Name  Age  Gender  Occupation
0      Sam   35    Male  Programmer
1    Ethan   30    Male     Manager
2     Noah   28    Male     Analyst
3   Prince   30    Male  Programmer
4    Chris   34    Male     Manager
5    Royce   25    Male     Analyst
6  Raechal   34  Female  Programmer
7     Mary   23  Female     Manager
8   Antony   34    Male     Analyst
9    Maria   35  Female     Analyst

# 6.Select the rows of the dataframe where the age is greater than or equal to 30.

In [89]:
age=df_frame[df_frame['Age']>=30]                 
print("Rows with age greater than or equal to 30 \n\n",age)

Rows with age greater than or equal to 30 

       Name  Age  Gender  Occupation
0      Sam   35    Male  Programmer
1    Ethan   30    Male     Manager
3   Prince   30    Male  Programmer
4    Chris   34    Male     Manager
6  Raechal   34  Female  Programmer
8   Antony   34    Male     Analyst
9    Maria   35  Female     Analyst


# 7.Convert this dataframe to a csv file and read that csv file, finally display the contents.


In [84]:
# Converting dataframe to csv
df_frame.to_csv('df_frame.csv')

# Reading csv file
df = pd.read_csv('df_frame.csv')

# Print the content

print(df)


   Unnamed: 0     Name  Age  Gender  Occupation
0           0      Sam   35    Male  Programmer
1           1    Ethan   30    Male     Manager
2           2     Noah   28    Male     Analyst
3           3   Prince   30    Male  Programmer
4           4    Chris   34    Male     Manager
5           5    Royce   25    Male     Analyst
6           6  Raechal   34  Female  Programmer
7           7     Mary   23  Female     Manager
8           8   Antony   34    Male     Analyst
9           9    Maria   35  Female     Analyst
